services:
  app:
    build: .
    container_name: music-league-tools-dev
    ports:
      - '5173:5173'
    volumes:
      # Mount source code for hot-reload
      - .:/app
      # Prevent node_modules from being overwritten
      - /app/node_modules
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true
